apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # IMPORTANT: Update this URL to your forked repository
    repoURL: https://github.com/SurajS27/Everyday-Project
    targetRevision: HEAD
    path: "Day 2/infrastructure/argocd-apps"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true