apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-self-healing-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SurajS27/Everyday-Project
    targetRevision: HEAD
    path: apps/my-self-healing-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true